name: Build consul-template

on:
  # schedule:
  #   - cron: "0 20 15,30 * *"
  workflow_dispatch:

jobs:
  build-consul-template:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "CT_VERSION=$(curl -fsSL https://api.github.com/repos/hashicorp/consul-template/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        id: docker_build_consul_template
        with:
          context: ./consul-template
          file: ./consul-template/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/consul-template:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/consul-template:${{ env.CT_VERSION }}
            ghcr.io/${{ github.repository }}/consul-template:latest
            ghcr.io/${{ github.repository }}/consul-template:${{ env.CT_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_consul_template.outputs.digest }}
